import { Token } from './types';

export const tokens: Token[] = [
  {
    id: '1',
    name: 'Rocket Pool ETH',
    abbreviation: 'rETH',
    logo: require('../../assets/images/token1.png'),
    amount: '4.00002',
    price: '$14,688.29',
  },
  {
    id: '2',
    name: 'Aerodrome',
    abbreviation: 'AERO',
    logo: require('../../assets/images/token2.png'),
    amount: '1,529.62',
    price: '$1,713.17',
  },
  {
    id: '3',
    name: 'Based Brett',
    abbreviation: 'BRETT',
    logo: require('../../assets/images/token3.png'),
    amount: '16,977.1573',
    price: '$668.90',
  },
  {
    id: '4',
    name: 'USD Coin',
    abbreviation: 'USDC',
    logo: require('../../assets/images/token4.png'),
    amount: '591.16',
    price: '$591.16',
  },
  {
    id: '5',
    name: 'Toshi',
    abbreviation: 'TOSHI',
    logo: require('../../assets/images/token5.png'),
    amount: '1,338,379',
    price: '$487.71',
  },
  {
    id: '6',
    name: 'Normie',
    abbreviation: 'NORMIE',
    logo: require('../../assets/images/token6.png'),
    amount: '6,806.5292',
    price: '$396.14',
  },
  {
    id: '7',
    name: 'Based Shiba Inu',
    abbreviation: 'BSHIB',
    logo: require('../../assets/images/token7.png'),
    amount: '918,309.86',
    price: '$260.80',
  },
];
