export const Images = {
  logo: require('./images/LogoBG.png'),
  waves: require('./images/waves.png'),
  land1: require('./images/land1.png'),
  land2: require('./images/land2.png'),
  profileicon: require('./images/profileicon.png'),
  scanner: require('./images/scanner.png'),
  secure: require('./images/secure.png'),
  assets: require('./images/assets.png'),
  explore: require('./images/explore.png'),
  home: require('./images/home.png'),
  trade: require('./images/trade.png'),
  down:require('./images/down.png'),
  buy : require('./images/buy.png'),
  earn : require('./images/earn.png'),
  recieve : require('./images/recieve.png'),
  send : require('./images/send.png'),
  coinlogo : require('./images/coinlogo.png'),
  tradelogo : require('./images/trade.png'),
  pros: require('./images/pros.png'),
  cross:require('./images/cross.png'),
  projects: require('./images/Projectsmain.png'),
  projectlogo: require('./images/projectlogo.png'),
  list1: require('./images/list1.png'),
  list2: require('./images/list2.png'),
  list3: require('./images/list3.png'),
  list4: require('./images/list4.png'),
  list5: require('./images/list5.png'),
  list6: require('./images/list6.png'),
  backscreen: require('./images/backscreen.png'),
  comment: require('./images/comment.png'),
  iconcircle:require('./images/iconcircle.png'),
  prosimage: require('./images/prosimage.png'),
  crossoverlay: require('./images/closeoverlay.png'),
  primary: require('./images/primary.png'),
  primary1: require('./images/primary1.png'),
  primary2: require('./images/primary2.png'),
  social: require('./images/social.png'),
  nfts: require('./images/nfts.png'),
  trade1: require('./images/trade1.png'),
  trade2: require('./images/trade2.png'),
  earn1: require('./images/earn1.png'),
  earn2: require('./images/earn2.png'),
  bottomhead: require('./images/bottomhead.png'),
  up: require('./images/up.png'),
  checked: require('./images/checked.png'),
  back: require ('./images/back.png'),
  probadge: require('./images/probadge.png'),
  checked1: require('./images/checked1.png'),
  securityicon:require('./images/securityicon.png'),
identity:require('./images/identity.png'),
connections:require('./images/connections.png'),
referrals:require('./images/referrals.png'),
notifications:require('./images/notifications.png'),
contacts:require('./images/contacts.png'),
helpsupport:require('./images/helpsupport.png'),
forward:require('./images/forward.png'),
pro:require('./images/pro.png'),
secureicon:require('./images/secureicon.png'),
tick:require('./images/tick.png'),
downarrow:require('./images/downarrow.png'),
refresh:require('./images/refresh.png'),
whitecross:require('./images/whitecross.png'),
vaulticon:require('./images/vaulticon.png'),
solanalogo: require('./images/solanalogo.png'),
solanabg: require('./images/solanabg.png'),
backarrow: require('./images/backarrow.png'),
copy: require('./images/COPY.png'),
pbottom: require('./images/profilebottomlogo.png'),
base: require('./images/baselogo.png'),
qr1: require('./images/QR.png'),
token1: require('./images/token1.png'),
token2: require('./images/token2.png'),
token3: require('./images/token3.png'),
token4: require('./images/token4.png'),
token5: require('./images/token5.png'),
token6: require('./images/token6.png'),
token7: require('./images/token7.png'),
token8: require('./images/token8.png'),
downarroww: require('./images/downarroww.png'),
searchicon: require('./images/searchicon.png'),
overlaybackground: require('./images/overlaybackground.png'),
tradebottom: require('./images/tradebottom.png'),
titanium:require('./images/titanium.png'),
insured:require('./images/insured.png'),
sent:require('./images/sent.png'),
received:require('./images/received.png'),
rocket:require('./images/rocket.png'),
cashout:require('./images/cashout.png'),
return:require('./images/return.png'),
solana:require('./images/solana.png'),
bothsolanabase:require('./images/bothsolanabase.png'),
etherium:require('./images/etherium.png'),
bitcoin:require('./images/bitcoin.png'),
sol:require('./images/sol.png'),
usd:require('./images/usd.png'),
dai:require('./images/dai.png'),
aero:require('./images/aero.png'),
bret:require('./images/bret.png'),
lido:require('./images/lido.png'),
search:require('./images/search.png'),
coinbase:require('./images/coinbase.png'),
nft1:require('./images/nft1.png'),
nft2:require('./images/nft2.png'),
nft3:require('./images/nft3.png'),
nft4:require('./images/nft4.png'),
nft5:require('./images/nft5.png'),
nft6:require('./images/nft6.png'),
nft7:require('./images/nft7.png'),
nft8:require('./images/nft8.png'),
failed:require('./images/failed.png'),
pending:require('./images/pending.png'),
cancel:require('./images/cancel.png'),
qr:require('./images/qr1.png'),
sync:require('./images/sync.png'),
swap:require('./images/swap.png'),
warning:require('./images/warning.png'),
sellerlogo:require('./images/sellerlogo.png'),
buyerlogo:require('./images/buyerlogo.png'),
basecardlogo: require('./images/basecardlogo.png'),
// launcharrow: require('./images/launcharrow.png'),
// tradecompletion: require('./images/tradecomplete.png'),
basebg: require('./images/basecardbg.png'),
hamburger:require('./images/hamburger.png'),
hamburgerbg:require('./images/hamburger.png'),
slb: require('./images/slb.png'),
profileheadlogo: require('./images/profileheadlogo.png'),
questionmark:require('./images/questionmark.png'),
cash:require('./images/cash.png'),
reddown:require('./images/reddown.png'),
greenup:require('./images/greenup.png'),
secure1: require('./images/secure1.png'),
swipearrow: require('./images/swipearrow.png')
}
